-- 코드를 입력하세요
SELECT A.USER_ID,	A.NICKNAME,	CONCAT(A.CITY, ' ', A.STREET_ADDRESS1, ' ', a.STREET_ADDRESS2) AS 전체주소,
 CONCAT(SUBSTRING(A.TLNO, 1, 3), '-', SUBSTRING(A.TLNO, 4, 4), '-', SUBSTRING(A.TLNO, 8)) AS 전화번호
from USED_GOODS_USER AS A
JOIN USED_GOODS_BOARD AS B
ON B.WRITER_ID=A.USER_ID
GROUP BY A.USER_ID
HAVING COUNT(B.WRITER_ID)>=3
ORDER BY A.USER_ID DESC

