-- 코드를 입력하세요
SELECT YEAR(a.SALES_DATE) AS YEAR, 
		MONTH(a.SALES_DATE) AS MONTH,
        b.GENDER AS GENDER, 
        COUNT(DISTINCT b.USER_ID) AS USERS
FROM USER_INFO b JOIN ONLINE_SALE a ON b.USER_ID = a.USER_ID
GROUP BY YEAR, MONTH, GENDER
HAVING GENDER IS NOT NULL 
ORDER BY YEAR, MONTH, GENDER