SELECT
  h.HISTORY_ID,
  ROUND(
    c.DAILY_FEE * (DATEDIFF(h.END_DATE, h.START_DATE) + 1)
    * (1 - IF(d.DISCOUNT_RATE IS NOT NULL, d.DISCOUNT_RATE, 0) / 100)
  , 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS c
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS h
  ON c.CAR_ID = h.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS d
  ON d.CAR_TYPE = c.CAR_TYPE
 AND d.DURATION_TYPE = CASE
       WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 90 THEN '90일 이상'
       WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 30 THEN '30일 이상'
       WHEN DATEDIFF(h.END_DATE, h.START_DATE) + 1 >= 7  THEN '7일 이상'
       ELSE NULL
     END
WHERE c.CAR_TYPE = '트럭'
ORDER BY FEE DESC, h.HISTORY_ID DESC;
